services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.rootless
    volumes:
      - .:/workspace
    working_dir: /workspace
    group_add:
      - dialout
    command: tail -f /dev/null
